# Generated by Django 4.1.3 on 2022-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='unTag',
            field=models.JSONField(default={}),
        ),
    ]
